#! /bin/sh

bspc config border_width        2
bspc config window_gap         15

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config leaf_monocle        true
bspc config focus_by_distance   true

bspc config focused_border_color "#6bbfa5"
bspc config presel_border_color "#c1c1bd"

bspc monitor -d I II III IV V VI VII VIII IX X

